TrajectoryPlannerROS : 
#Robot Configuration Parameters
 max_vel_x: 0.3 # max velocity in x 
 min_vel_x: 0.1
 
 max_vel_theta: 0.8
 min_vel_theta: -1.0
 min_in_place_vel_theta: 0.5

 acc_lim_x: 0.5 # limitation of acceleration
 acc_lim_y: 0.0
 acc_lim_theta: 0.6

# Goal Tolerance Parameters
 xy _goal_tolerance: 0.05
 yaw_goal_tolerance: 0.05

#Differential-drive robot configuration
 holonomic_robot: false #

#Forward Simulation Parameters
 sim_time: 1.2
 vx_samples: 40
 vtheta_samples: 40
 sim_granularity: 0.05
