local_costmap: 
  global_frame: odom # the VO coordinate
  robot_base_frame: base_footprint # the body coordinate
  update_frequency: 10.0 
  publish_frequency: 10.0
  transform_tolerance: 0.5
  static_map: false # 
  rolling_window: true # using dynamic windows to search
  width: 3 # the width of local map(m)
  height: 3 # the height of local map(m)
  resolution: 0.1 # the fenbianlv(m)
